[theme]
base = "dark"
primaryColor = "#7F5AF0"
backgroundColor = "#0F0F13"
secondaryBackgroundColor = "#16161A"
textColor = "#FFFFFE"
font = "sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
